apiVersion: apps/v1
kind: Deployment
metadata:
  name: templatedsecret-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: templatedsecret-controller
  template:
    metadata:
      labels:
        app: templatedsecret-controller
    spec:
      containers:
        - name: controller
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 200Mi
