apiVersion: apps/v1
kind: Deployment
metadata:
  name: templatedsecret-controller
spec:
  selector:
    matchLabels:
      app: templatedsecret-controller
  template:
    metadata:
      labels:
        app: templatedsecret-controller
    spec:
      containers:
        - name: controller
          resources:
            requests:
              memory: 50Mi
            limits:
              memory: 100Mi
              cpu: 500m
