apiVersion: apps/v1
kind: Deployment
metadata:
  name: templated-secret-controller
spec:
  selector:
    matchLabels:
      app: templated-secret-controller
  template:
    metadata:
      labels:
        app: templated-secret-controller
    spec:
      containers:
        - name: controller
          resources:
            requests:
              memory: 50Mi
            limits:
              memory: 100Mi
              cpu: 500m
