---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: templated-secret-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: templated-secret-controller
subjects:
  - kind: ServiceAccount
    name: templated-secret-controller
    namespace: templated-secret-dev
