[settings]
pipx_uvx = true

[env]
# Directory paths
ROOT_DIR = "{{config_root}}"

[tools]
cosign = '2.6.0'                     #renovate: packageName=sigstore/cosign
jq = '1.8.1'                            #renovate: packageName=jqlang/jq
kubectl = '1.34.1'                      #renovate: datasource=github-tags packageName=kubernetes/kubectl versioning=^kubernetes-(?<version>.*)$
kubeconform = '0.6.7'                   #renovate: packageName=yannh/kubeconform
kustomize = '5.7.1'                     #renovate: packageName=kubernetes-sigs/kustomize
stern = '1.32.0'                        #renovate: packageName=stern/stern  
"pipx:uv" = '0.8.9'                     #renovate: packageName=astral-sh/uv
go = '1.25.1'                           #renovate: datasource=golang-version packageName=golang/go
goreleaser = "2.8.2"
vivid = "latest"
syft = "latest"
