apiVersion: v1
kind: Secret
metadata:
  name: secret1
type: Opaque
stringData:
  key1: val1
  key2: val2
---
apiVersion: v1
kind: Secret
metadata:
  name: secret2
type: Opaque
stringData:
  key3: val3
  key4: val4
---
apiVersion: templatedsecret.starstreak.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: combined-secret
spec:
  inputResources:
    - name: secret1
      ref:
        apiVersion: v1
        kind: Secret
        name: secret1
    - name: secret2
      ref:
        apiVersion: v1
        kind: Secret
        name: secret2
  template:
    type: mysecrettype
    data:
      key1: $(.secret1.data.key1)
      key2: $(.secret1.data.key2)
      key3: $(.secret2.data.key3)
      key4: $(.secret2.data.key4)
