---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  ports:
    - name: http
      port: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap1
data:
  key1: val1
  key2: val2
---
apiVersion: templatedsecret.starstreak.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: non-secret-inputs
spec:
  serviceAccountName: input-resource-reader # used to fetch input resources
  inputResources:
    - name: service
      ref:
        apiVersion: v1
        kind: Service
        name: service1
    - name: config
      ref:
        apiVersion: v1
        kind: ConfigMap
        name: configmap1
  template:
    metadata:
      labels:
        key1: value1
      annotations:
        key1: value1
    type: mysecrettype
    stringData:
      key1: combined-value-$(.config.data.key1)-$(.config.data.key2)
      key2: $(.config.data.key2)
      port: $(.service.spec.ports[?(@.name=="http")].port)
      host: $(.service.spec.clusterIP)

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: input-resource-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: input-resource-reader
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: input-resource-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: input-resource-reader
subjects:
  - kind: ServiceAccount
    name: input-resource-reader
