apiVersion: v2
name: templated-secret-controller
description: A Helm chart for the Templated Secret Controller
type: application
version: 0.20.1
appVersion: "0.20.1"
kubeVersion: ">=1.16.0-0"
home: https://github.com/drae/templated-secret-controller
sources:
  - https://github.com/drae/templated-secret-controller
keywords:
  - kubernetes
  - secrets
  - templating
maintainers:
  - name: drae
    url: https://github.com/drae/
