apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: templated-secret

images:
  - name: controller
    newName: ghcr.io/drae/templated-secret-controller
    newTag: stable

patchesStrategicMerge:
  - patches/deployment.yaml
