apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "templated-secret-controller.fullname" . }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    {{- include "templated-secret-controller.labels" . | nindent 4 }}
spec:
  {{- if not (and .Values.autoscaling (eq .Values.autoscaling.enabled true)) }}
  replicas: {{ .Values.replicaCount | int }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "templated-secret-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "templated-secret-controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "templated-secret-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: controller
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.metrics.enabled }}
            - --metrics-bind-address={{ .Values.metrics.bindAddress }}
            {{- else }}
            - --metrics-bind-address=0
            {{- end }}
            {{- if .Values.probes.enabled }}
            - --health-probe-bind-address={{ .Values.probes.bindAddress }}
            {{- else }}
            - --health-probe-bind-address=0
            {{- end }}
            {{- if .Values.namespace }}
            - --namespace={{ .Values.namespace }}
            {{- end }}
            - --enable-cross-namespace-secret-inputs={{ .Values.crossNamespace.enabled }}
            - --warn-on-unwatched-cross-namespaces={{ .Values.crossNamespace.warnOnUnwatched }}
          {{- if .Values.probes.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: {{ .Values.probes.port }}
            initialDelaySeconds: {{ .Values.probes.readinessInitialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readinessPeriodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readinessFailureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: {{ .Values.probes.port }}
            initialDelaySeconds: {{ .Values.probes.livenessInitialDelaySeconds }}
            periodSeconds: {{ .Values.probes.livenessPeriodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.livenessFailureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}