apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "templated-secret-controller.fullname" . }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    {{- include "templated-secret-controller.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: ["templatedsecret.starstreak.dev"]
    resources: ["secrettemplates"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["templatedsecret.starstreak.dev"]
    resources: ["secrettemplates/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets", "serviceaccounts", "serviceaccounts/token"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "templated-secret-controller.fullname" . }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    {{- include "templated-secret-controller.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "templated-secret-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "templated-secret-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
