{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "templated-secret-controller.fullname" . }}-metrics
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    {{- include "templated-secret-controller.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    {{- include "templated-secret-controller.selectorLabels" . | nindent 4 }}
{{- end }}