#@ load("@ytt:data", "data")
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
  - image: templatedsecret-controller
    path: .
    docker:
      buildx:
        #! Always rebuild image
        pull: false
        noCache: false
        file: Dockerfile.dev
        buildkit: true
        rawOptions:
          -  #@ "--build-arg=SGCTRL_VER="+data.values.dev.version
          #@ if/end data.values.dev.platform != "":
          -  #@ "--platform="+data.values.dev.platform
        #@ end

#@ if/end data.values.dev.push_images:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
  - image: templatedsecret-controller
    newImage: #@ data.values.dev.image_repo
