name: Continuous Integration
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - "docs/**"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"
  workflow_dispatch:

jobs:
  call-common:
    uses: ./.github/workflows/common.yml
    with:
      img: ghcr.io/drae/templated-secret-controller
      tag: dev
