name: Kind Cluster E2E tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - "docs/**"
  push:
    branches:
      - develop
    paths-ignore:
      - "docs/**"
      - "*.md"
  workflow_dispatch:

jobs:
  run-tests:
    name: e2e tests on kind
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: kinder

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1" # Specify exact version instead of using go-version-file

      # Set up Docker BuildX with a builder that supports multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: image=moby/buildkit:buildx-stable-1

      - name: Build controller image
        run: |
          make docker-build PLATFORMS=linux/amd64

      - name: Load image to Kind
        run: |
          kind load docker-image --name kinder ${IMG}:${TAG}

      - name: Deploy CRDs
        run: |
          make manifests
          kubectl apply -f config/kustomize/base/crds/

      - name: Deploy controller
        run: |
          # Create namespace if it doesn't exist
          kubectl create namespace templatedsecret-system --dry-run=client -o yaml | kubectl apply -f -

          # Create deployment and rbac resources
          kubectl apply -f config/kustomize/base/rbac/

          # Apply deployment with the correct image
          cat <<EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: templatedsecret-controller
            namespace: templatedsecret-system
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: templatedsecret-controller
            template:
              metadata:
                labels:
                  app: templatedsecret-controller
              spec:
                containers:
                - name: controller
                  image: ${IMG}:${TAG}
                  resources:
                    limits:
                      cpu: 100m
                      memory: 128Mi
                    requests:
                      cpu: 100m
                      memory: 128Mi
                serviceAccountName: templatedsecret-controller
          EOF

          # Wait for deployment to be ready
          kubectl -n templatedsecret-system wait deployment/templatedsecret-controller --for=condition=Available --timeout=60s

      - name: Run E2E tests
        run: |
          mkdir -p tmp
          TEMPLATEDSECRET_E2E_NAMESPACE=templatedsecret-test ./hack/test-e2e.sh
