name: Kind Cluster E2E tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - "docs/**"
  push:
    branches:
      - develop
    paths-ignore:
      - "docs/**"
      - "*.md"
  workflow_dispatch:

jobs:
  run-tests:
    name: e2e tests on kind
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: kinder
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install Carvel Tools
        uses: carvel-dev/setup-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          only: ytt, kapp, kbld
          ytt: v0.45.4
          kapp: v0.58.0
          kbld: v0.37.5
      # Run benchmark with `go test -bench` and stores the output to a file
      - name: Install sg and run e2e tests on kind
        run: |
          set -e -x
          kubectl version

          ytt -f config/package-bundle/config -f config/dev | kbld -f- > kbld.out 2> kbldmeta.out
          cat kbldmeta.out | tail -n 1 | sed 's/.*final: templatedsecret-controller -> \(.*\)$/\1/p'  | tail -n 1 | xargs kind load docker-image --name kinder
          kapp deploy -a sg -f kbld.out -c -y

          mkdir tmp
          SECRETGEN_E2E_NAMESPACE=templatedsecret-test eval './hack/test-e2e.sh'
