apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: templated-secret-controller
  name: templated-secret-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: templated-secret-controller
  template:
    metadata:
      labels:
        app: templated-secret-controller
    spec:
      serviceAccountName: templated-secret-controller
      containers:
        - name: controller
          image: controller:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 30Mi
            limits:
              cpu: 100m
              memory: 50Mi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          args:
            - --metrics-bind-address=:8080
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
