apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - rbac.yaml
  - service.yaml
  - crds/templatedsecret.starstreak.dev_secrettemplates.yaml

namespace: templated-secret

labels:
  - pairs:
      app: templated-secret-controller

images:
  - name: controller
    newName: ghcr.io/drae/templated-secret-controller
    newTag: latest
