apiVersion: v1
kind: ServiceAccount
metadata:
  name: templated-secret-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: templated-secret-controller
rules:
  - apiGroups: ["templatedsecret.starstreak.dev"]
    resources: ["secrettemplates"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["templatedsecret.starstreak.dev"]
    resources: ["secrettemplates/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets", "serviceaccounts", "serviceaccounts/token"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: templated-secret-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: templated-secret-controller
subjects:
  - kind: ServiceAccount
    name: templated-secret-controller
    namespace: templated-secret
