apiVersion: v1
kind: Service
metadata:
  labels:
    app: templated-secret-controller
  name: templated-secret-controller-metrics
  namespace: templated-secret
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: templated-secret-controller
