apiVersion: v1
kind: Service
metadata:
  name: templatedsecret-controller-metrics
  labels:
    app: templatedsecret-controller
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: templatedsecret-controller
